### PR TITLE
Always mark RRDP servers as broken after failed update.

### PR DESCRIPTION
**Pull request by partim**
This will cause falling back to rsync if accessing the repository via RRDP fails.

### CODE REVIEW

**Comment by ties** [comment]
Hi,

Since I expect the moment at which RP instances detect an RRDP repo to fail are correlated, I am concerned with many RP instances contacting an rsync repository at the same time (thundering herd problem).

When is the next update from rsync scheduled after RRDP fails?

**Comment by lolepezy** [comment]
To continue on the question from @ties: is it possible to have some sort of random delay between routinator notices that RRDP is unavailable and actually uses rsync? It would make the whole process much smoother for the repository side. We are not sure we can/want deploy infrastructure that would reliably handle 2K rsync connections downloading 60K of objects within several minutes window, so it would be nice to spread this load somehow.

**Comment by ties** [comment]
> To continue on the question from @ties: is it possible to have some sort of random delay between routinator noticing that RRDP is unavailable and actually using rsync? It would make the whole process much smoother for the repository side. We are not sure we can/want deploy infrastructure that would reliably handle 2K rsync connections downloading 60K of objects within several minutes window, so it would be nice to spread this load somehow.

My proposal would be to wait for "half the rsync interval + random value from a uniform distribution from 0..."rsync interval". That way the average instance updates one "rsync interval" later while spreading out the load as much as possible.

**Comment by partim** [comment]
Actually, there’s already quite a bit of randomness built in. Routinator starts a new fetch `refresh` seconds after it finished the last one. So the time depends on both when it was started exactly and the overall duration of each consecutive validation run. With `refresh` defaulting to 10 minutes (and the majority of installation apparently sticking to it), I would expect a fairly even distribution of the clients first hitting rsync over a ten minute interval.

One problem I now realize is that if rsync also fails (for instance because the rsync service is has a connection limit), currently Routinator will _not_ use the RRDP data anymore. If it never used rsync, it will not have any data at all.

Maybe doing this whole fallback in such an ad hoc fashion is a bad idea. It is probably better to leave it for 0.9 and the planned redesign of fetching after all.

**Comment by ties** [comment]
> Actually, there’s already quite a bit of randomness built in. Routinator starts a new fetch `refresh` seconds after it finished the last one. So the time depends on both when it was started exactly and the overall duration of each consecutive validation run. With `refresh` defaulting to 10 minutes (and the majority of installation apparently sticking to it), I would expect a fairly even distribution of the clients first hitting rsync over a ten minute interval.

I will need to do a more thorough analysis, but my estimate is that spreading the clients out over the rsync update interval would really have a big impact on the load on rsync servers, it is a 6x reduction in load.

Do you think routinator will keep the rsync directories when rrdp works again? If so I will try to get some data on the duration of rsync runs for both completely expired, relatively recent, and empty rsync directories.

**Comment by partim** [comment]
> I will need to do a more thorough analysis, but my estimate is that spreading the clients out over the rsync update interval would really have a big impact on the load on rsync servers, it is a 6x reduction in load.

The requests should basically be spread exactly the same way as the RRDP requests are right now. Admittedly I haven’t checked how that actually looks, but that should be fairly easy.

> Do you think routinator will keep the rsync directories when rrdp works again?

I believe it currently does – I think there isn’t actually any cleanup done.

> If so I will try to get some data on the duration of rsync runs for both completely expired, relatively recent, and empty rsync directories.

I’d love to hear your thoughts on operational considerations for as graceful a fallback as possible.

Given that there might be some unintended consequences from just falling back in the current architecture, I’ll will close this PR for now. We will properly implement fallback as part of the new architecture.

**Pull request closed without merging**
