### PR TITLE
dockerfile to support multiarchitecture

### PR DESCRIPTION
**Pull request by bladeswords**
Bump alpine to latest version
adjust build path to support building on different architectures such as ARM.
Addresses #763

### CODE REVIEW

**Comment by ximon18** [comment]
Thanks @bladeswords.

> Bump alpine to latest version

Is that related to the main purpose of the PR or something you did as well at the same time but unrelated?

Thanks,

Ximon

**Comment by bladeswords** [comment]
> Is that related to the main purpose of the PR or something you did as well at the same time but unrelated?

I did that at the same time as removing the specific platform target.  Specifying the x86_64-alpine-linux-musl target prevented this from building on an arm system.  Removing the target allowed the compiler to select and build for the right platform.

BTW, I have never used rust before so I am very unfamiliar with the terminology and tooling - sorry.

**Comment by ximon18** [comment]
> BTW, I have never used rust before so I am very unfamiliar with the terminology and tooling - sorry.

Absolutely no need to apologize, the contribution and input is extremely welcome!

**Comment by ximon18** [comment]
> > Is that related to the main purpose of the PR or something you did as well at the same time but unrelated?
> 
> I did that at the same time as removing the specific platform target. Specifying the x86_64-alpine-linux-musl target prevented this from building on an arm system. Removing the target allowed the compiler to select and build for the right platform.
> 
> BTW, I have never used rust before so I am very unfamiliar with the terminology and tooling - sorry.

I've included the change to not pass `--target` in PR #764, thanks!

**Pull request closed without merging**
