### PR TITLE
Offer json and jsonext under the /api/v1/ tree.

### LINKED ISSUE #591: Make `/json` available under `/api/v1/json`
For the API and front end work @density215 is doing, it would be more practical to have the data at the `/json` endpoint available under `/api/v1/json` (as well).

### PR DESCRIPTION
**Pull request by partim**
Fixes #591

### CODE REVIEW

**Review by DRiKE — APPROVED** [review]

**Comment by AlexanderBand** [comment]
@partim, did you take @density215's additional requests from #591 into account, e.g. `/api/v1/vrp/<PREFIX>/select`?

**Comment by partim** [comment]
I did not. Let me fix that.

**Comment by partim** [comment]
We’ll postpone this until 0.10.1. To avoid confusion, I’ll mark the PR as a draft.

**Comment by ties** [comment]
Do you have any idea about the timeline for the "old" `/json`/etc endpoints? For now the endpoints under `/api/v1/` are an addition. But do you have a long term plan for this?

**Comment by partim** [comment]
There’s no plan to remove the old paths.

**Comment by partim** [comment]
This has been superseded by #707.

**Pull request closed without merging**
